import re

with open('utils.ts', 'r') as f:
    content = f.read()

content = content.replace('"Macro Structural Thesis: Cross-Asset Institutional Flows\\nThe aggregate Commitment of Traders (COT) data reveals massive rotational capital flows across global asset classes. We are witnessing a clear divergence where \\\'Smart Money\\\' is aggressively reallocating capital in response to shifting central bank liquidity cycles and geopolitical friction.\\n\\nMetals, currencies, and energy are completely decoupling. The institutional footprint shows distinct accumulation in specific safe-haven or high-yield assets, while actively liquidating exposure in highly levered risk-on sectors. This is not a retail-driven market; this is a pure, systematic institutional rotation. Understanding these hidden flows provides a massive edge for daily timeframe positioning, allowing us to align with the deepest pockets in the market."',
"`Macro Structural Thesis: Cross-Asset Institutional Flows\\nThe aggregate Commitment of Traders (COT) data reveals massive rotational capital flows across global asset classes. We are witnessing a clear divergence where 'Smart Money' is aggressively reallocating capital in response to shifting central bank liquidity cycles and geopolitical friction.\\n\\nMetals, currencies, and energy are completely decoupling. The institutional footprint shows distinct accumulation in specific safe-haven or high-yield assets, while actively liquidating exposure in highly levered risk-on sectors. This is not a retail-driven market; this is a pure, systematic institutional rotation. Understanding these hidden flows provides a massive edge for daily timeframe positioning, allowing us to align with the deepest pockets in the market.`")

content = content.replace('"Tactical Macro Playbook:\\n1. Asset Selection: Isolate the 2 or 3 specific commodities/currencies showing the most aggressive week-over-week Net Change in institutional positioning. Ignore the rest.\\n2. Execution Framing: Wait for major macroeconomic data releases (e.g., NFP, CPI) to create artificial \\\'whipsaws\\\'. Use these engineered liquidity sweeps to enter in the direction of the dominant COT trend.\\n3. Risk Management: Never trade the initial news spike. Wait for the New York session daily close to confirm the true institutional intent before committing capital."',
"`Tactical Macro Playbook:\\n1. Asset Selection: Isolate the 2 or 3 specific commodities/currencies showing the most aggressive week-over-week Net Change in institutional positioning. Ignore the rest.\\n2. Execution Framing: Wait for major macroeconomic data releases (e.g., NFP, CPI) to create artificial 'whipsaws'. Use these engineered liquidity sweeps to enter in the direction of the dominant COT trend.\\n3. Risk Management: Never trade the initial news spike. Wait for the New York session daily close to confirm the true institutional intent before committing capital.`")

with open('utils.ts', 'w') as f:
    f.write(content)
